// Scenarios + step options + i18n + ground rules KB
window.SCENARIOS_DATA = [
  { id:'s501', icon:'⚖', color:'c-blue',
    en:{ title:'Visa cancellation under s 501', sub:'Long-term resident · 12-month assault · non-refoulement claim ignored',
         facts:'Plaintiff is a 39-year-old NZ-born long-term Australian resident. Visa cancelled under Migration Act s 501 after a 12-month sentence for assault. Tribunal addressed the non-refoulement claim in 5 words. Adverse ASIO assessment was not put for response.'},
    kr:{ title:'s 501에 따른 비자 취소', sub:'장기 거주자 / 폭행 12개월 형 / 비-반환 주장 미고려',
         facts:'원고는 39세 뉴질랜드 출생 호주 장기 거주자이다. 폭행 12개월 형 후 Migration Act s 501에 따라 비자가 취소되었다. tribunal은 비-반환 주장을 5단어로 처리했다. 불리한 ASIO 평가는 응답을 위해 제시되지 않았다.'} },
  { id:'schlieske', icon:'◐', color:'c-coral',
    en:{ title:'Deportation arranged after failed extradition', sub:'Two failed extradition attempts → deportation order with foreign police receiving',
         facts:'Plaintiff is a foreign national. Two extradition attempts failed. The Minister then ordered deportation, coordinated with foreign police to receive the plaintiff at the airport.'},
    kr:{ title:'인도 실패 후 추방 주선', sub:'두 차례 인도 실패 → 외국 경찰이 인도받는 추방 명령',
         facts:'원고는 외국 국적자이다. 두 차례 인도 시도가 실패했다. 이후 장관이 추방을 명령하면서 외국 경찰이 공항에서 인도받도록 조율했다.'} },
  { id:'argos', icon:'⌅', color:'c-teal',
    en:{ title:'Development approval — third-party challenge', sub:'Competing supermarket challenges planning approval',
         facts:'Plaintiff operates a supermarket within 2km of a planning approval granted to a competing supermarket developer. Plaintiff alleges traffic and trade impact assessment was not conducted.'},
    kr:{ title:'개발 승인 — 제3자의 다툼', sub:'경쟁 마트가 계획 승인을 다툼',
         facts:'원고는 경쟁 마트 개발자에게 부여된 계획 승인 부지로부터 2km 내에서 마트를 운영한다. 원고는 교통·상권 영향 평가가 실시되지 않았다고 주장한다.'} },
  { id:'reg', icon:'☷', color:'c-ochre',
    en:{ title:'Challenge to delegated legislation', sub:'Regulation extending "misbehaviour" to all imprisonable offences',
         facts:'A regulation made under a federal Act defines "misbehaviour" by reference to any imprisonable offence and triggers automatic disqualification. The empowering Act\'s purpose is to maintain board integrity.'},
    kr:{ title:'위임입법에 대한 다툼', sub:'"비위"를 모든 징역 가능 범죄로 확장한 규정',
         facts:'연방 법률에 따라 제정된 규정이 "비위"를 모든 징역 가능 범죄로 정의하고 자동 자격 박탈 사유로 삼는다. 수권법의 목적은 위원회의 청렴 유지이다.'} },
  { id:'undisclosed', icon:'⊕', color:'c-violet',
    en:{ title:'Adverse decision on undisclosed material', sub:'Country information used without putting it for comment',
         facts:'A protection visa was refused based on country information obtained from a closed source. The applicant was not given an opportunity to comment on the specific information.'},
    kr:{ title:'미공개 자료에 근거한 불이익 결정', sub:'폐쇄적 자료를 의견 제출 기회 없이 사용',
         facts:'폐쇄적 출처에서 얻은 출신국 정보를 근거로 보호 비자가 거부되었다. 신청자는 그 구체적 정보에 대해 의견을 제출할 기회를 받지 못했다.'} }
];

window.STEPS_DATA = {
  jurisdiction: {
    en:{ label:'Jurisdiction', help:'Pick all available federal/state forums.' },
    kr:{ label:'관할', help:'가능한 연방·주 관할을 모두 선택.' },
    multi:true,
    options:[
      {id:'adjr', en:'ADJR Act', kr:'ADJR Act', note_en:'Cth admin "decision" "under enactment".', note_kr:'연방 행정 "결정" "수권법에 따른".'},
      {id:'39b', en:'s 39B(1) Judiciary Act', kr:'s 39B(1) Judiciary Act', note_en:'Cth officer; common law writs.', note_kr:'연방 공무원; common law 영장.'},
      {id:'75v', en:'s 75(v) Constitution', kr:'s 75(v) 헌법', note_en:'Constitutional writs; cannot be ousted.', note_kr:'헌법적 영장; 배제 불가.'},
      {id:'state', en:'State Supreme Court', kr:'주 대법원', note_en:'Kirk supervisory jurisdiction.', note_kr:'Kirk 감독 관할.'}
    ]
  },
  justiciability: {
    en:{ label:'Justiciability', help:'Multiple gateways may apply.' },
    kr:{ label:'심사적격', help:'여러 관문이 동시에 적용될 수 있음.' },
    multi:true,
    options:[
      {id:'bond', en:'Bond decision', kr:'Bond 결정', note_en:'Final / operative / determinative.', note_kr:'최종 / 실질 / 결정적.'},
      {id:'admin', en:'Administrative character', kr:'행정적 성격', note_en:'Not legislative or judicial.', note_kr:'입법·사법이 아님.'},
      {id:'tang', en:'Tang under enactment', kr:'Tang 수권법에 따른', note_en:'Two limbs satisfied.', note_kr:'2단계 모두 충족.'},
      {id:'m61', en:'M61 workaround', kr:'M61 우회', note_en:'Outsourced step → s 39B/75(v).', note_kr:'외주 단계 → s 39B/75(v).'},
      {id:'skip-leg', en:'Skip — delegated legislation', kr:'위임입법은 건너뛰기', note_en:'Different framework (W1).', note_kr:'다른 분석틀(W1).'}
    ]
  },
  grounds: {
    en:{ label:'Grounds of review', help:'Pick all that apply — substantive and procedural.' },
    kr:{ label:'심사 사유', help:'적용 가능한 사유를 모두 선택 — 실체·절차.' },
    multi:true,
    options:[
      {id:'pf', en:'Hearing rule (PF)', kr:'청문 규칙(PF)', note_en:'Annetts default; Lam practical injustice.', note_kr:'Annetts 기본; Lam 실질적 부정의.', cases:['annetts','lam']},
      {id:'bias', en:'Apprehended bias', kr:'추정 편향', note_en:'Ebner two-step.', note_kr:'Ebner 2단계.', cases:['ebner']},
      {id:'mandatory', en:'Mandatory consideration', kr:'의무 고려사항', note_en:'Peko-Wallsend.', note_kr:'Peko-Wallsend.', cases:['peko']},
      {id:'irrelevant', en:'Irrelevant consideration', kr:'무관 고려사항', note_en:'Beyond statutory scope.', note_kr:'법적 범위 밖.', cases:[]},
      {id:'purpose', en:'Improper purpose', kr:'부정한 목적', note_en:'Schlieske dominant operative purpose.', note_kr:'Schlieske 지배적 작용 목적.', cases:['schlieske']},
      {id:'tickner', en:'Active consideration (Tickner)', kr:'적극적 고려(Tickner)', note_en:'No delegation of mental act.', note_kr:'정신적 행위 위임 불가.', cases:['tickner']},
      {id:'m1', en:'Reasonable consideration (M1/2021)', kr:'합리적 검토(M1/2021)', note_en:'Read identify understand evaluate.', note_kr:'읽기 식별 이해 평가.', cases:['m1-2021']},
      {id:'inflexible', en:'Inflexible policy application', kr:'정책의 경직된 적용', note_en:'Green v Daniels.', note_kr:'Green v Daniels.', cases:['green']},
      {id:'li', en:'Legal unreasonableness (Li)', kr:'법적 비합리성(Li)', note_en:'Always-JE final-decision.', note_kr:'최종 결정 항상-JE.', cases:['li']},
      {id:'illogical', en:'Illogicality (SZMDS)', kr:'비논리성(SZMDS)', note_en:'High threshold.', note_kr:'높은 문턱.', cases:['szmds']},
      {id:'noevid', en:'No evidence', kr:'무증거', note_en:'Critical finding without basis.', note_kr:'근거 없는 핵심 인정.', cases:[]},
      {id:'jf', en:'Jurisdictional fact (Enfield)', kr:'관할권적 사실(Enfield)', note_en:'Court decides on evidence.', note_kr:'법원이 증거로 판단.', cases:['enfield']},
      {id:'proportion', en:'Proportionality', kr:'비례성', note_en:'Vanstone for delegated legislation.', note_kr:'위임입법에는 Vanstone.', cases:['vanstone']},
      {id:'legality', en:'Legality principle', kr:'합법성 원칙', note_en:'Coco; Evans.', note_kr:'Coco; Evans.', cases:['coco','evans']}
    ]
  },
  materiality: {
    en:{ label:'Materiality', help:'Pick the rule that fits this ground.' },
    kr:{ label:'중요성', help:'사유에 맞는 규칙을 선택.' },
    multi:false,
    options:[
      {id:'realistic', en:'Realistic possibility (Hossain / LPDT)', kr:'현실적 가능성(Hossain / LPDT)', note_en:'No reconstruction.', note_kr:'재구성 금지.'},
      {id:'wzarh', en:'WZARH inferred (PF)', kr:'WZARH 추론(PF)', note_en:'Submissions readily inferred.', note_kr:'추가 주장이 쉽게 추론됨.'},
      {id:'always', en:'Always-JE (skip materiality)', kr:'항상-JE(중요성 생략)', note_en:'Bias / Kirk PF / final unreasonableness / JF.', note_kr:'편향 / Kirk PF / 최종 비합리성 / JF.'},
      {id:'na', en:'N/A — delegated legislation', kr:'해당 없음 — 위임입법', note_en:'No materiality requirement.', note_kr:'중요성 요건 없음.'}
    ]
  },
  remedies: {
    en:{ label:'Remedies', help:'Choose remedies matching grounds.' },
    kr:{ label:'구제수단', help:'사유에 맞는 구제수단 선택.' },
    multi:true,
    options:[
      {id:'certiorari', en:'Certiorari', kr:'Certiorari', note_en:'Quashing the decision.', note_kr:'결정의 파기.'},
      {id:'mandamus', en:'Mandamus', kr:'Mandamus', note_en:'Compel re-decision.', note_kr:'재결정 강제.'},
      {id:'prohibition', en:'Prohibition', kr:'Prohibition', note_en:'Stop further unlawful act.', note_kr:'이후의 위법 행위 정지.'},
      {id:'declaration', en:'Declaration', kr:'Declaration', note_en:'Statement of legal position.', note_kr:'법적 지위의 선언.'},
      {id:'injunction', en:'Injunction', kr:'Injunction', note_en:'Restrain action.', note_kr:'행위의 제한.'}
    ]
  }
};

window.I18N = {
  en:{
    appTitle:'Australian Admin Law Study',
    subtitle:'administrative law · interactive study',
    nav:{ weeks:'Course content', scenario:'Scenario analyser', db:'Cases & doctrine', glossary:'Glossary', flash:'Flashcards', quiz:'Mixed quiz' },
    tabs:{ overview:'Overview', tree:'Decision tree', detail:'Detail', cases:'Cases', quiz:'Quiz' },
    week:'Week',
    keyPoints:'Key points',
    keyCases:'Key cases',
    studyAt:'Study notes',
    notesPlaceholder:'Write your study notes here. Stays for this session only.',
    search:'Search cases, keywords, doctrine…',
    filterTopic:'Topic',
    filterCategory:'Category',
    all:'All',
    rule:'Rule',
    when:'When to use',
    issue:'Issue',
    conclusion:'Conclusion',
    keywords:'Keywords',
    facts:'Facts',
    principle:'Principle established',
    howApply:'How to apply',
    cite:'Citation',
    close:'Close',
    flashFront:'Case → Rule',
    flashBack:'Rule → Case',
    flashFlip:'Tap to flip',
    flashAgain:'Again',
    flashHard:'Hard',
    flashGood:'Good',
    flashEasy:'Easy',
    flashProgress:'Progress',
    flashDeck:'Deck',
    flashRemaining:'remaining',
    flashDone:'Session complete — review again or pick another deck.',
    flashRestart:'Restart deck',
    quizStart:'Start mixed quiz',
    quizQ:'Question',
    quizOf:'of',
    quizCorrect:'Correct',
    quizWrong:'Not quite',
    quizNext:'Next question',
    quizScore:'Score',
    quizFinal:'Final score',
    quizRestart:'New mix',
    sScenario:'Choose scenario',
    sCustom:'Or describe your own facts',
    sFacts:'Facts',
    sStep:'Step',
    sNext:'Next',
    sBack:'Back',
    sIRAC:'IRAC skeleton',
    sIssue:'Issue',
    sRule:'Rule',
    sApp:'Application',
    sConcl:'Conclusion',
    sReset:'Reset',
    print:'Print',
    lang:'한국어',
    legend:{branch:'Click any node to follow that branch'},
    hint:{tree:'Click any node to follow that branch.', case:'Click an icon badge to open the case panel.'}
  },
  kr:{
    appTitle:'호주 행정법 스터디',
    subtitle:'행정법 · 인터랙티브 학습',
    nav:{ weeks:'주차별 강의', scenario:'시나리오 풀어보기', db:'판례·법리', glossary:'용어 사전', flash:'플래시카드', quiz:'섞기 퀴즈' },
    tabs:{ overview:'개요', tree:'결정 흐름', detail:'자세히', cases:'관련 판례', quiz:'쪽지시험' },
    week:'주차',
    keyPoints:'핵심 포인트',
    keyCases:'핵심 판례',
    studyAt:'학습 메모',
    notesPlaceholder:'이번 세션에만 남는 메모. 새로고침하면 사라진다.',
    search:'판례명·키워드·법리 내용을 검색해 봐…',
    filterTopic:'주차',
    filterCategory:'유형',
    all:'전체',
    rule:'법리',
    when:'언제 쓰나',
    issue:'쟁점',
    conclusion:'결론',
    keywords:'키워드',
    facts:'사실관계',
    principle:'세운 원칙',
    howApply:'쓰는 법',
    cite:'인용',
    close:'닫기',
    flashFront:'판례 → 법리',
    flashBack:'법리 → 판례',
    flashFlip:'탭해서 뒤집기',
    flashAgain:'다시',
    flashHard:'어려움',
    flashGood:'좋음',
    flashEasy:'쉬움',
    flashProgress:'진행률',
    flashDeck:'덱',
    flashRemaining:'장 남음',
    flashDone:'한 바퀴 다 돌았다. 다시 돌리거나 다른 덱으로 가 봐.',
    flashRestart:'다시 시작',
    quizStart:'섞기 퀴즈 시작',
    quizQ:'문항',
    quizOf:'/',
    quizCorrect:'정답',
    quizWrong:'아쉽다',
    quizNext:'다음',
    quizScore:'점수',
    quizFinal:'최종 점수',
    quizRestart:'다시 섞기',
    sScenario:'시나리오 고르기',
    sCustom:'또는 직접 사실관계를 적어도 된다',
    sFacts:'사실관계',
    sStep:'단계',
    sNext:'다음',
    sBack:'이전',
    sIRAC:'IRAC 답안 골격',
    sIssue:'쟁점',
    sRule:'법리',
    sApp:'적용',
    sConcl:'결론',
    sReset:'처음으로',
    print:'인쇄',
    lang:'English',
    legend:{branch:'노드를 누르면 그 갈래로 들어간다'},
    hint:{tree:'노드를 누르면 그 갈래로 들어간다.', case:'아이콘 배지를 누르면 판례 카드가 열린다.'}
  }
};
